### ISSUE TITLE
demand contoller panel not showing

### ISSUE THREAD

**Issue by E1Gordo** [thanasip/DemandController#1]
Hi FALC - as per comment on steam workshop re panel not showing when i moved the button - here is what ive tried and my pc specs ....

i9 1290 - rtx 3090 - 32 corsair vengeance - rog strix z690-f - samsung 980 pro 2tb - benq 32" 4k

the panel position in the xml file is 200,200
the button position was APPROX (i forgot to check before editing the xml !! sorry ) 95,130
i moved the button round different areas of the screen and it did change the X,Y coords in the xml whilst i was still in game
i moved the button as close as i could get "by eye" to 200,200 ( actually 194,207) thinking thats about where the panel should be - just FYI it ended up approx 35mm from top left corner of my screen - not sure if thats relevant tho )
ive tried ALL resolutions with ALL aspect ratios and windowed / fullscreen (thats 40 minutes of my life im not gonna get back !!!)
ive clicked the button and use crtl/alt/d

NONE of the above made the panel appear and the 200,200 panel position NEVER changed in the xml so im not sure that my original idea is correct

coding is absolutely out of my league so i cant really help with anymore ideas im afraid however if there IS anything you want me to try drop me an email 

i know you guys do this for fun (??? ;-) ) and sometimes get comments which in my opinion don't take this into account e.g. this mod is rubbish - it doesn't work etc etc so i DO appreciate what you've done and hope you can sort it

all the best

**Comment by thanasip** [comment]
Hi Gordo, thanks for the detailed explanation!

Just to make sure I've understood correctly, have you seen the Demand Controller "window" at _any_ time since the 21/02 update with the button, or has it not worked at all since then? It sounds like it stopped working after you moved the button, but before then it did work for a time?

The difficulty I'm having is that it's actually positioned _relative_ to the screen size (i.e. a fixed distance from the top left corner of the screen) precisely to avoid this issue - changing the resolution should have no effect on the relative position of the button and panel (you may be able to see this by changing aspect rations and resolutions; the button position should not change significantly other than the difference in aspect _ratio_)

Could you try editing the panel position in the XML to something around the centre of your screen (so for a 16:9 4K you want x = 1920, y = 1080)? The window should appear to the bottom right of the centre point at this setting. Also, when trying the shortcut, first double check that it's enabled (it should default to true) and try holding ctrl+alt and tapping D rather than trying to press them all at once (especially important if the sim is running slowly due to a big city or w/e).

Thanks for the kind words - this is a perverse type of fun, in a strange way :P

**Comment by E1Gordo** [comment]
hiya - couple things i remembered - not sure if relevant .....
couple patches ago the mod was showing in the main / first screen (continue / load game / new game etc) under options but wasnt showing in the options screen in game although it did work ok with ctrl/alt/d  - i am just tapping the D by the way ;-) and fyi ... i dont do "running slowly" with my PC's lol :P
im just restarting the game and ive edited the xml to 1920,1080 but ive got loads of mods/assets it take 3 or 4 minutes each time (134 mods and nearly 10k assets - amazing the stuff we keep downloading eh !! ) so i'll give you a shout soon as possible

**Comment by E1Gordo** [comment]
nope :_( - still no luck
both the options are enabled in the mod options screen and ive tried changing the panel x,y to all sorts - including negative numbers (no idea why i did that tbh but you never know i suppose)
and finally just to be clear cos i keep forgetting to make sure you know IT HAS ALWAYS WORKED PERFECTLY AFTER ALL THE UPDATES UNTIL I MOVED THE BUTTON TO THE TOP LEFT OF THE SCREEN - immediately after the latest update i loaded the game, clicked the button and the panel showed up and i maxed out the RCI just to check - i thought .. great hes fixed it, disabled with the tick box and then moved the button - when i tried again later the panel didnt show

**Comment by E1Gordo** [comment]
ive just had a thought but you could maybe set the panel to appear AS CLOSE TO the button position as possible probably to the right of it as its likely most shortcut icons are often on the left of the screen when players re-arrange them ?? just a thought tho .... youre the modder ;-)

**Comment by E1Gordo** [comment]
actually thats probably bollocks !! - looking at the xml it looks like you set x,y positions as absolutes not relatives so forget that ... i'll keep thinking but as i said im no coder ;-)

**Comment by thanasip** [comment]
Interestingly, the default configuration is exactly what you describe; the button to the left of the panel. The positions happen to look absolute because they are relative to the top left corner of the entire screen; but they are bound in such a way that they are always positioned relatively rather than absolutely. In this case, 200, 200 simply means 200 px right and 200 px down from the top left of the screen (wherever that happens to be).

The thing I'm struggling with is that I just can't replicate the issue. What I might do in the meantime is introduce a "reset" button in either the options menu, or as a right click on the button or something, to put the panel and button back to default (destroy/recreate). 

In the meantime, the only thing I can think of is unsub from the mod, delete the XML file, and resub; if that doesn't work, then the only possibility I can think of is a clash of some kind? Have you installed any other mods since Demand Controller, around the time it stopped working?

**Comment by E1Gordo** [comment]
i understand re the x,y so it does seem strange - i'll check on any newish mods and let you know - i did unsub / resub but didnt delete the xml so ill do that now

**Comment by thanasip** [comment]
I'm about to push an update that fixes a couple of little bugs and adds a "Reset UI" button to options menu - should be about 5 minutes

**Comment by thanasip** [comment]
That's been pushed, let me know how you go :)

**Comment by E1Gordo** [comment]
sorted ;-) ..... however !!
i clicked the button and the panel came up just next to it fine - closed panel - moved button - clicked and NO PANEL
right clicked button - yes to reset position and it came back and has been fine ever since EVEN IF  i move the button again
but bottom line  - nice one cheers bud

**Comment by thanasip** [comment]
That's very strange, but I'm glad it worked!
I'm gonna close this issue for now, but this isn't really a fix as much as a workaround - if I get more reports I'll look into it further

Thanks for your help!

**Comment by E1Gordo** [comment]
no probs - ill keep an eye on it and post on steam if something goes tits if thats ok

**Comment by thanasip** [comment]
Sure, thanks
